### ISSUE TITLE
Support for android 1.5

### ISSUE THREAD

**Issue by igala** [havlenapetr/FFMpeg#14]
Is it possibel to run the project on Android 1.5?

I tried to do so and it failed in loading the jniaudio and jnivideo libraries.

Do I need to build them for 1.5 system?
Is it possible?
How do I do that?

**Comment by havlenapetr** [comment]
yes, it is, but you must recompile jnivideo and jniaudio for 1.5 version

**Comment by igala** [comment]
Tx, do you have guide or instructions how do I do that?

**Comment by havlenapetr** [comment]
no, you must look into my android_frameworks_base in native you will find my jnivideo and jniaudio. these libs are only wrappers into android surface_flinger and audio manager, so you must update them for 1.5 version

**Comment by igala** [comment]
ok, I built the jnivideo and jniaudio on a cupcake system.
I rebuilt the ffmepg_jni with the new libraries.
When I try to run the application on the emulator it says that it could not load the ffmpeg_jni library (though it loaded the  jnivideo and jniaudoi with no probelm):

DEBUG/dalvikvm(735): Trying to load lib /data/data/cz.havlena.ffmpeg.ui/lib/libffmpeg_jni.so 0x43598c18
 INFO/dalvikvm(735): Unable to dlopen(/data/data/cz.havlena.ffmpeg.ui/lib/libffmpeg_jni.so): Cannot find library
 DEBUG/FFMpeg(735): Couldn't load lib: ffmpeg_jni - Library ffmpeg_jni not found
 DEBUG/FFMpegPlayerActivity(735): Error when inicializing ffmpeg: Couldn't load native libs

Do you have an idea what is wrong? is the ffmpeg_jni code compatibale with cupcake?

Igal

**Comment by igala** [comment]
ok, I see that Android 1.5 has a but in loading dependencies of 3rd party native libraries 
(ie. libjnivideo and libjniaudio)  what do you suggest?

Can they be linked statically?
