### ISSUE TITLE
linker error: undefined reference to `AndroidSurface_updateSurface' .....

### ISSUE THREAD

**Issue by gascani** [havlenapetr/FFMpeg#21]
When I compile the project I have the errors: How can i sove them?

SharedLibrary  : libffmpeg_jni.so
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::VideoDriver_updateSurface()':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:75: undefined reference to`AndroidSurface_updateSurface'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::VideoDriver_getPixels(int, int, void**)':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:70: undefined reference to`AndroidSurface_getPixels'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::VideoDriver_unregister()':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:65: undefined reference to`AndroidSurface_unregister'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::VideoDriver_register(_JNIEnv*, _jobject*)':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:60: undefined reference to`AndroidSurface_register'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::AudioDriver_write(void*, int)':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:53: undefined reference to`AndroidAudioTrack_write'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::AudioDriver_reload()':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:48: undefined reference to`AndroidAudioTrack_reload'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::AudioDriver_stop()':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:43: undefined reference to`AndroidAudioTrack_stop'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::AudioDriver_flush()':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:38: undefined reference to`AndroidAudioTrack_flush'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::AudioDriver_set(int, unsigned int, int, int)':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:33: undefined reference to`AndroidAudioTrack_set'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::AudioDriver_start()':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:22: undefined reference to`AndroidAudioTrack_start'
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/obj/local/armeabi/libmediaplayer.a(output.o): In function `Output::AudioDriver_unregister()':
/home/marco/sviluppo/havlenapetr-FFMpeg-cc53d91/jni/libmediaplayer/output.cpp:17: undefined reference to`AndroidAudioTrack_unregister'
collect2: ld returned 1 exit status

**Comment by gascani** [comment]
I'm working with Ubuntu + ndk r5b

**Comment by gascani** [comment]
solved: the problem are ndk r5b. With the ndk 4 it's ok!

**Comment by bdictator** [comment]
EXCELLENT!!!
THANKS A MILLION!!
