### ISSUE TITLE
Audio-Video Synchronization

### ISSUE THREAD

**Issue by sarvadaman** [havlenapetr/FFMpeg#27]
I am trying to play a .ts video file/stream but I am facing audio video sync issue. Could anyone please suggest me anything for this.
Thanks
Sarvadaman

**Comment by dextorer** [comment]
AFAIK, no one knows a solution to this. havlena itself said that he was at this point, too.

**Comment by havlenapetr** [comment]
here is tutorial: http://dranger.com/ffmpeg/tutorial05.html but is pretty hard to understand, I will try to implement it, but someone could try it too and send me patch

**Comment by dextorer** [comment]
i am trying to add H.264 support to your project. once completed, if you want, you can integrate my work with yours. after that i will try to solve the synch issue. it seems, though, that method invocations (setFrameSkip, setFrameSize, ..) don't affect the video playback at all; is it just me or even you?

**Comment by liuzongan** [comment]
I hope you ffmpeg completed ,send me .email:    liuzongan1985@163.com   

thank you

**Comment by icmoon** [comment]
Dear  dextorer,
I would like to compile havlenapetr's FFMpeg with my own compiled x264 in cygwin.

## I saw the following errors 

Compile thumb  : ffmpeg_jni <= cmdutils.c
SharedLibrary  : libffmpeg_jni.so
C:/fm/ffmpeg/obj/local/armeabi-v7a/libavcodec.a(libx264.o): In function `X264_close':
C:/fm/ffmpeg/jni/libffmpeg/libavcodec/libx264.c:146: undefined reference to`x264_encoder_close'
C:/fm/ffmpeg/obj/local/armeabi-v7a/libavcodec.a(libx264.o): In function `X264_frame':
C:/fm/ffmpeg/jni/libffmpeg/libavcodec/libx264.c:92: undefined reference to`x264_picture_init'
C:/fm/ffmpeg/jni/libffmpeg/libavcodec/libx264.c:107: undefined reference to `x264_encoder_encode'
C:/fm/ffmpeg/jni/libffmpeg/libavcodec/libx264.c:113: undefined reference to`x264_encoder_delayed_frames'
C:/fm/ffmpeg/obj/local/armeabi-v7a/libavcodec.a(libx264.o): In function `X264_init':
C:/fm/ffmpeg/jni/libffmpeg/libavcodec/libx264.c:156: undefined reference to`x264_param_default'
C:/fm/ffmpeg/jni/libffmpeg/libavcodec/libx264.c:300: undefined reference to `x264_encoder_open_116'
C:/fm/ffmpeg/jni/libffmpeg/libavcodec/libx264.c:310: undefined reference to`x264_encoder_headers'
collect2: ld returned 1 exit status

## make: **\* [/cygdrive/c/fm/ffmpeg/obj/local/armeabi-v7a/libffmpeg_jni.so] Error 1

belows is my android.mk

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

IN_NDK := true

LOCAL_CFLAGS := -D__STDC_CONSTANT_MACROS

WITH_CONVERTOR := true
WITH_PLAYER := false

ifeq ($(WITH_PLAYER),true)
LOCAL_CFLAGS += -DBUILD_WITH_PLAYER
endif

ifeq ($(WITH_CONVERTOR),true)
LOCAL_CFLAGS += -DBUILD_WITH_CONVERTOR
endif

LOCAL_C_INCLUDES += \
    $(LOCAL_PATH)/../libffmpeg \
    $(LOCAL_PATH)/../libx264 \
    $(LOCAL_PATH)/../libmediaplayer \
    $(LOCAL_PATH)/../include

LOCAL_SRC_FILES := \
    onLoad.cpp \
    com_media_ffmpeg_FFMpegAVFrame.cpp \
    com_media_ffmpeg_FFMpegAVInputFormat.c \
    com_media_ffmpeg_FFMpegAVRational.c \
    com_media_ffmpeg_FFMpegAVFormatContext.c \
    com_media_ffmpeg_FFMpegAVCodecContext.cpp \
    com_media_ffmpeg_FFMpegUtils.cpp

ifeq ($(WITH_CONVERTOR),true)
LOCAL_SRC_FILES += \
    com_media_ffmpeg_FFMpeg.c \
    ../libffmpeg/cmdutils.c
endif

ifeq ($(WITH_PLAYER),true)
LOCAL_SRC_FILES += \
    com_media_ffmpeg_FFMpegPlayer.cpp
#com_media_ffmpeg_android_FFMpegPlayerAndroid.cpp
endif

ifeq ($(IN_NDK),true)  
LOCAL_LDLIBS := -llog
else
LOCAL_PRELINK_MODULE := false
LOCAL_SHARED_LIBRARIES := liblog
endif

#LOCAL_SHARED_LIBRARIES := libjniaudio libjnivideo
#LOCAL_STATIC_LIBRARIES := libavcodec libavformat libavutil libpostproc libswscale libmediaplayer
LOCAL_STATIC_LIBRARIES := libx264 libavcodec libavformat libavutil libpostproc libswscale

LOCAL_MODULE := libffmpeg_jni

## include $(BUILD_SHARED_LIBRARY)

any hint to help me to get out of these problems 
Thank you

**Comment by dextorer** [comment]
i tried many times to add the x264 support on this project. i was successful in compiling, but i couldn't see no changes in the player's behaviour: that is to say, i was still unable to playback .H264 video files. sorry mate.

**Comment by sparklets** [comment]
@dextorer  can you tell me the way to get the frames of video and audio , I want to get video frames all in bitmap array

**Comment by jollysandhu71** [comment]
Hi 
I want to run HD file through FFMPEG and X264 . Pls Could you tell or guide to me how to integrate X264 with FFMPEG . Thanx to u

**Comment by havlenapetr** [comment]
check ffmpeg project (in config.h enable x264 flag)
