### ISSUE TITLE
is this project a player or a converter?

### ISSUE THREAD

**Issue by iorisjh** [havlenapetr/FFMpeg#28]
I have compiled it and it results in a mediaplayer in the emulator,but in your readme file,it looks like a media converter.
could you explain it ? thanks!

**Comment by havlenapetr** [comment]
It is both, when I started this project it was only converter, now it is 
player too, I deleted converter activity from project but in history you 
should find it.

P.

iorisjh wrote:

> I have compiled it and it results in a mediaplayer in the emulator,but in your readme file,it looks like a media converter.
> could you explain it ? thanks!
