### ISSUE TITLE
I met three errors when compiling and using this project

### ISSUE THREAD

**Issue by jackrun2000** [havlenapetr/FFMpeg#3]
1. I use ndk-1.6_r1 environment (like you use) to compile and get the error: com_media_ffmpeg_android_FFMpegPlayerAndroid.cpp:306: error: too few arguments to function, line 306:      if(VideoDriver_unregister() != ANDROID_SURFACE_RESULT_SUCCESS). The related description is in drivers_map.h: line 8: typedef int (_audioDriver_register_t) (JNIEnv_, jobject);
   I think it would be  typedef int (*audioDriver_register_t) (void); so I changed and the compiler can go on and get the libffmpeg_jni.so. I want to know the change is right or not.
2. when I use NDK-r4b to compile, another error appears: undefined reference to `__android_log_print in many files. I think it is caused with lack of android/log.h, because I can not find the log.h in the directory, so please attach the log.h in your program list. But I still want to know why in NDK-1.6_r1, it can be compiled successfully?
3. The problems that unload the jni libraries in eclipse: with android version 1.5 and 1.6, the project can be built successfully ( in android 2.0 or 2.2, fail to build). The similar errors appear like another person:I/dalvikvm(  241): Unable to dlopen(/data/data/cz.havlena.ffmpeg.ui/lib/libjniaudio.so): Cannot load library: link_image[1638]:    30 could not load needed library 'libbinder.so' for 'libjniaudio.so' (load_library[984]: Library 'libbinder.so' not found)
   I/dalvikvm(  241): Unable to dlopen(/data/data/cz.havlena.ffmpeg.ui/lib/libjnivideo.so): Cannot load library: link_image[1638]:    30 could not load needed library 'libskia.so' for 'libjnivideo.so' (load_library[984]: Library 'libskia.so' not found)
   I think the libjniaudio.so and libjnivideo.so should be re-compiled by myself, but I don't know how to compile them correctly, please give me some directions. Thank you.

**Comment by havlenapetr** [comment]
1. compile debug branch
2. it is in liblog.so declared and header is in android/log.h, maybe in laters NDKs was in root include dir?? You must search your NDK before you write issue
3. you must copy libjnivideo.so and libjniaudio.so into lib/armeabi of your project for eclipse, which pack them into apk. If you run this project on not froyo OS you will have errors because some libraries don't be there or have other name and dalvik can't find them

**Comment by jackrun2000** [comment]
There would be some setting path different between NDK-1.6_r1 and NDK-r4b in compiling target. For simplicity, I just copy the liblog.so to the dir where libjniaudio.so and libjnivideo.so are to link to linffmpeg_jni.so, and modify the Android.mk  to add liblog like that: LOCAL_SHARED_LIBRARIES := libjniaudio libjnivideo liblog, then the error: "undefined reference to `__android_log_print" will not appear in NDK-r4b environment.

I run the project in emulator and really copy the libjnivideo.so and libjniaudio.so into lib/armeabi directory, but the unloaded errors still exist. Based on the talking between you and Seesky, I know what you said is right.  because I run the project in Eclair, there  are really not some libraries, such as libsurfaceflinger_client.so. I will try to make libjniaudio.so and libjnivideo.so in Eclair, if I have some result, I will tell you first.

**Comment by jackrun2000** [comment]
I tried several times and passed finally. Here is my configuration changed for elair: from the eclair source, copy your native directory to frameworks/base/, modify the file of native/video/jni/Android.mk to add libui to LOCAL_SHARED_LIBRARIES list and replace libsurfaceflinger_client with libsurfaceflinger, modify surface.cpp to replace #include <surfaceflinger/Surface.h> with #include <ui/Surface.h>, add libjniaudio.so and libjnivideo.so to the end of myandroid/build/core/prelink-linux-arm.map, then I get the libjniaudio.so and libjnivideo.so in out/target/product/generic/obj/lib for eclair. I try them in my emulator, the result is exactly beyond my imagination.  It will be better if your project can fit any android version. Anyway, Thank you for your porting. If possible, I will send the three .so for eclair to you for testing by other people.

**Comment by havlenapetr** [comment]
yes great, if you can play any video by my ffmpeg port you will see that video and audio are out of sync, maybe if you will have time you can solve this problem, i haven't much time for programming to this project right now

**Comment by jackrun2000** [comment]
Today, I tested your project in a real machine and found the video and audio played out of sync exactly. Maybe it spent much time in decoding or there are other problems. I will try to find the reason, but I am worried about my capability will delay this task.

**Comment by lhzhang** [comment]
hi,havlenapetr
   I am glad to share to your exchange. I see  your FFmpeg directory where has the libfaac directory.But i don't know how to compile the libfaac (/FFMpeg /jni/libfaac ). Awaing your reply. Thanks.

**Comment by lhzhang** [comment]
if i want to add the library, such as libdc1394 ,libdirac,libfaac,libfaad,libfaadbin,libgsm  ,libmp3lame,libspeex,libvorbis,libx264 and libxvid . We know  these library can be copiled with ffmpeg in linux (eg.ubuntu ). I am not  aware of the processes. Can you give me some advice ?

**Comment by lhzhang** [comment]
hi, jackrun2000  
I also tested the project in simulator. It's great . As you said ,
the video and audio played out of sync exactly. Now i am  finding the reason .
If i  have some results ,i will tell you. 
Feel free to  contact me.~~

**Comment by jackrun2000** [comment]
hi,ihzhang,
if you want to compile the libfaac and add it into libffmpeg_jni, you just modify the Android.mk in jni directory to add libfaac at the end of LOCAL_STATIC_LIBRARIES := libavcodec libavformat libavutil libpostproc libswscale, then you can get a new libffmpeg_jni with libfaac. If you want to add other lib, I think there is the similar way.

I am trying to use SDL surface to change the display feature of ffmpeg for modifying the sync, but have not the result yet.

**Comment by lhzhang** [comment]
Thank you for your reply in time. Now I will go to debug it following what you said. 

```
```

 It's great. Successful compile.

**Comment by lhzhang** [comment]
hi, jackrun2000  
   Maybe you have a look this (http://code.google.com/p/ffmpeg4iphone/). SDL is made use of FFMpeg for iPhone.

**Comment by jackrun2000** [comment]
hi, lhzhang
Thank you for your mention. My platform  is not  iPhone, but it would be useful as the reference.

**Comment by eefolks** [comment]
hi:jackrun2000

i tested this project in simulator (eclair )and i can get the nice video.
but when i try it in the moto's milestone,i get a bad video.

i delete android:screenOrientition="landscape" from manifest.xml
and set the Milestone in portrait,i can get the nice video .

when i set the phone in landscape ,i get a bad video.

Do you have the same problem in a real machine which use eclair os?
sorry ! i can't explicitly describe how bad the video is ,but i can send you the snapshot of the bad video.

**Comment by jackrun2000** [comment]
hi, eefoiks
when I play pure video (no audio playback), I can get good view whether in emulator or real machine, but when I add audio playback in the video, the video will be thrilled. You don't send me the snapshot, I know the result and I have known the reason, that is because the video decoding and the audio decoding are in the same flow, when in audio decoding time, it will block the video playing. It should be resolved to introduce thread processing.

**Comment by eefolks** [comment]
hi :jackrun2000 and everyone

the newest project of havlenapetr  is multi thread,so audio decoding will not block the video playing.

anybody get  perfect video by running this project in MOTO's milestone (Eclair) ?????

**Comment by jackrun2000** [comment]
hi, eefolks
thank you for your mention. I have tried the newest project in emulator and real machine, I can get good video and audio, but the they are not synchronized. I will try to modify to meet good feature. 
I have no MOTO machine, so I can only give you some suggestions: you can add some log messages after audio decode and video decode to see (with logcat command) if there are errors out or not. I am afraid that the memory would be out of the range, because the project will need of much memory space.

**Comment by dcypang** [comment]
eefolks ,

I am having troubling displaying my video when my DROID is in landscape mode, do you know how I should resolve this problem ?

Thanks,
Derek
