### ISSUE TITLE
Is it possible to use fade in/out effects?

### ISSUE THREAD

**Issue by sanalbakis** [havlenapetr/FFMpeg#33]
Hi,
I just wanted to ask, if you know how to use fade-in/out effects in android+ffmpeg?
the normal usage is: 
  ffmpeg -i input_file -vfilters fade=in:0:30 output_file .
when I try the command like this, program quits, in debug i see that it is not a known command (or something like that).
I have registered the fade in effect in 
config.h,
the filters are also added in libavfilter :
  allfilters.c
  vf_fade.c
  makefile

Thanks for your help..

**Comment by havlenapetr** [comment]
yes it is, but you must write jni methods, which will call it

**Comment by sanalbakis** [comment]
Hi, thank you for your answer. 
Can you please give me a little information that I can focus myself into. 
Where should I write this function? in Java or in jni folder? 
Thank you.

**Comment by havlenapetr** [comment]
if you want to call it from java side, you must write it in java and jni too, but if you want to use this effects allways, you can write this only in native code

**Comment by sanalbakis** [comment]
i want to use it with a fade in / fade out button. so I should write in both way. thank you for your info . 
in JNI should es c language or c++ ? 
Actually I only need fade in / fade out. is it also possible without ffmpeg? 
sorry for the basic questions. I just wanted to focus myself for my university project.

**Comment by havlenapetr** [comment]
I think that fade in and fade out are simple effects, when user starts playing audio(or video) you will constantly increase volume into some level(which was setted, before you starts from min) and than you must check track's time and when audio(or video) will be almost on the end you will decrease volume to min.

**Comment by sanalbakis** [comment]
yes, but it is only if user plays. i need to save/write a new video file with fade-in/fade-out effect. a new same quality video with fade effects.
thanks

**Comment by havlenapetr** [comment]
so this, you must do in ffmpeg native code, you must search it and use it, I don't know where it is in code, I am very busy

**Comment by sanalbakis** [comment]
thank you again for your answer. Yes, I just wanted to be informed. because I had really no idea which file I should edit. 
I am using an older version of you which video converts. 
there is a file it is called like under JNI "android/ffmpeg_native??.c" sorry, i am not in front of my computer. Is this file maybe?
Regards

**Comment by sanalbakis** [comment]
hello again, 
i am now at my computer. the file is: jni/android/android_media_ffmpeg.c 
is it that file that I should edit? Thanks.
