### ISSUE TITLE
render error

### ISSUE THREAD

**Issue by tsingien** [havlenapetr/FFMpeg#39]
when play a video,get screen like this:
<img src="http://hi.csdn.net/attachment/201108/2/1684663_1312252229ZWWT.png"/>
test phone is htc g7.
width of test video is 496px. other width is OK.

**Comment by havlenapetr** [comment]
hi this is bug in my render library, I fixed this I think but I didn't push it out yet, so i will do it in few days

**Comment by tsingien** [comment]
thanks
