### ISSUE TITLE
 Couldn't load lib: jniaudio

### ISSUE THREAD

**Issue by aminMlive** [havlenapetr/FFMpeg#42]
D/dalvikvm( 4127): Trying to load lib /data/data/cz.havlena.ffmpeg.ui/lib/libjniaudio.so 0x40514dc0

D/FFMpeg  ( 4127): Couldn't load lib: jniaudio - Cannot load library: reloc_library[1311]:    67 cannot locate '_ZN7android10AudioTrack3setEijiiijPFviPvS1_ES1_iRKNS_2spINS_7IMemoryEEEb'...

D/dalvikvm( 4127): Trying to load lib /data/data/cz.havlena.ffmpeg.ui/lib/libjnivideo.so 0x40514dc0

D/dalvikvm( 4127): Added shared lib /data/data/cz.havlena.ffmpeg.ui/lib/libjnivideo.so 0x40514dc0

D/dalvikvm( 4127): No JNI_OnLoad found in /data/data/cz.havlena.ffmpeg.ui/lib/libjnivideo.so 0x40514dc0, skipping init

D/dalvikvm( 4127): Trying to load lib /data/data/cz.havlena.ffmpeg.ui/lib/libffmpeg_jni.so 0x40514dc0

D/FFMpeg  ( 4127): Couldn't load lib: ffmpeg_jni - Cannot load library: link_image[1962]:    67 could not load needed library 'libjniaudio.so' for 'libffmpeg_jni.so' (find_library[1219]:    67 'libjniaudio.so' failed to load previously)

D/FFMpegPlayerActivity( 4127): Error when inicializing ffmpeg: Couldn't load native libs

how can i do ?

**Comment by jollysandhu71** [comment]
I have also same issue but could not solve it . Let me know how can solve it

**Comment by kmark** [comment]
Same exact issue when testing on my Droid X2 running Gingerbread 2.3.3. I get this error when compiled with NDK R5b and the latest NDK R6

**Comment by kukudy** [comment]
Have the same problem on T20 (2.3.3). Help is needed.

**Comment by aminMlive** [comment]
http://blog.csdn.net/piaozhiye/article/details/6363512

**Comment by jollysandhu71** [comment]
That above link is not given any solution of running issue. Still it is coming in debugging .

**Comment by kmark** [comment]
And I'd love to see a solution in English as well.

**Comment by nadavrub** [comment]
The problem is still there, the above link doesn't provide a solution
