### ISSUE TITLE
Video surface issue , when playing any video android.

### ISSUE THREAD

**Issue by Mobiloitte** [havlenapetr/FFMpeg#43]
Using FFMpeg library android now i am able to only create :
( 1. ) libffmpeg_jni.so
(2.) libjniaudio.so
(3.) libjnivideo.so

Now sound coming but video does not appear on surface with independent resolution size.

How to handle this case  when using your library  , is this bug  able to handle or not?  if yes then plz help me easily steps i am

working on this issue large time not getting way of success , loosed lot of time .

**Comment by Mobiloitte** [comment]
Please give me guideline how to run this code for any independent video resolution file.

**Comment by Mobiloitte** [comment]
Using FFMpeg library android now i am able to only create :
( 1. ) libffmpeg_jni.so
(2.) libjniaudio.so
(3.) libjnivideo.so

how to play resolution independent video on surface.

**Comment by cdavidyoung** [comment]
Have you been able to update the ffmpeg files with the latest from the ffmpeg website or are you using the source files that originally came with havlenapetr / FFMpeg?

**Comment by Mobiloitte** [comment]
i am using the original code come with  havlenapetr / FFMpeg library .is Need to update  with new ffmpeg lib replacement ? 

yes or NO? Please reply me Here i am not able to see video on surface on sound occur .

**Comment by cdavidyoung** [comment]
I don't know.  I guess it depends on whether the havlenapetr / FFMpeg works for you.  For me I am needing to convert a series of images to a video.  I am hoping that the havlenapetr / FFMpeg will work.  It would be nice to be able to upgrade to the latest code if necessary.  I have not tried it yet except to notice that havlenapetr added Android.mk to the folders.

**Comment by Mobiloitte** [comment]
When replacing havlenapetr / FFMpeg -ffmpeg api with latest api then Error occur.With havlenapetr / FFMpeg sampe not error occur , it compile successfully , audi working properly but video not on surface. Please resolve my issue.

**Comment by cdavidyoung** [comment]
Did the error occur when you were building or when you ran the app?

I just tried all 4 types of video files with this player on the Android and
none of them played.  All of them play on Windows with VLC so I am not sure
what is going on with the video surface.  I am using ffmpeg strictly for
encoding.

**Comment by Mobiloitte** [comment]
When i am compiling code using havlenapetr / FFMpeg -ffmpeg api  then application successfully installed on device , only facing issue regarding video issue only audio sound comes video not show on surface .I am able to share you apk for test . video not putting on surface only audio sound occur.

**Comment by Mobiloitte** [comment]
I am not getting another sample  which works for video play from sdcard on surface using ffmpeg.

I am using github this code  https://github.com/havlenapetr/FFMpeg, lib.so file creating success but video not showing on surface i can able to share you apk.

http://halosystechnologies.com/FTP-LOCATION/ftp-user15/FFMpeg.apk

**Comment by milanmanvarr** [comment]
can any one have solved this issue? i am facing same as.
