### ISSUE TITLE
"error: utils/Log.h: No such file or directory" in Cygwin and NDK

### ISSUE THREAD

**Issue by ycmmonkey** [havlenapetr/FFMpeg#5]
Dear havlenapetr:
    I found many head files have wrong path ,and some head file such as TypeHelpers.h are not exist，please tell me how to fix it ,thanks,and sorry for my poor English.

**Comment by havlenapetr** [comment]
compile debug branch

**Comment by ycmmonkey** [comment]
Thank you,finally I fixed head files path and other errors,and compiled successfully.

**Comment by igala** [comment]
Hi Guys,

I have exactly the same probelm and compiling the debug branch didn't help.

Can you please tell where is: "TypeHelpers.h"

Can you please help?
Tx

**Comment by ycmmonkey** [comment]
TypeHelpers.h is in android source project
