### ISSUE TITLE
Video image corrupted when FFMpegMovieViewAndroid display screen set to landscape mode. (Portrait mode works perfectly!)

### ISSUE THREAD

**Issue by dreamflash** [havlenapetr/FFMpeg#9]
Here is the steps to reproduce the bug.
1. Target platform is Froyo.
2. Set "Screen orientation" to "landscape" mode in the file AndroidManifest.xml
3. Play any video file and observe the playback image is corrupted or heavily skewed.
    (video works perfectly in portrait mode)

First, I thought this might be the display matrix problem, so I have tried apply skewed and/or rotate 90 matrix to the doUpdateSurface() function inside libjnivideo.so library. but image still comes out incorrectly. It seems the problem really comes out from the java side. (Surface etc)
Havlenapetr, can you take a look into this issue. Thanks

**Comment by dcypang** [comment]
Did anyone has a solution to this issue ?

**Comment by dcypang** [comment]
I just hacked the issue by fixing the display size to 800x600 on a DROID device. i.e. on FFMpegMovieViewAndroid.java, in openVideo(), add mSurfaceHolder.setFixedSize(800, 600); before mPlayer.setDisplay(mSurfaceHolder);

**Comment by dreamflash** [comment]
Confirmed. both fixes from havlenapetr and dcypand work, it solved the video corrupted in landscape mode. Thanks

//---------------------------------------------------------
From: havlenapetr

try this in FFMpegMovieViewAndroid class:

private void openVideo() {
try {
mSurfaceHolder.setFixedSize(800, 600);
mPlayer.setDisplay(mSurfaceHolder);
mPlayer.prepare();
} catch (IllegalStateException e) {
Log.e(TAG, "Couldn't prepare player: " + e.getMessage());
} catch (IOException e) {
Log.e(TAG, "Couldn't prepare player: " + e.getMessage());
}
}
//---------------------------------------------------------

**Comment by alexcohn** [comment]
The problem is the auto-scaling provided by the OS. Instead of hard-coding the screen size, simply set 

```
<uses-sdk android:minSdkVersion="3" android:targetSdkVersion="4"/>
```

in the AndroidManifest.xml file.
